### ISSUE TITLE
SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by devmount** [mrahtz/tensorflow-pos-tagger#1]
Hi there, thanks for this nice example of a POS tagger in tensorflow.
Unfortunately I cannot run the *demo.py* - it always throws the following error:

```
$ python demo.py
Enter a sentence to be annotated:
This is a sentence
Traceback (most recent call last):
  File "demo.py", line 19, in <module>
    sentence = input('Enter a sentence to be annotated:\n')
  File "<string>", line 1
    This is a sentence
                     ^
SyntaxError: unexpected EOF while parsing
```

What is required for your scripts to work?
I'm using the ubuntu bash on the linux subsystem on windows 10. Training with the *train.py* was successfull.
Thanks!

**Comment by devmount** [comment]
Ok, I found the solution:
*demo.py*:19 needs to use `raw_input` instead of `input` method in Python2. In Python3 it's working fine.

**Comment by mrahtz** [comment]
Thanks for the heads up. Have updated the README to emphasise that python3 is expected.
