### ISSUE TITLE
KeyError: "The name 'Adam' refers to an Operation not in the graph."

### ISSUE THREAD

**Issue by gary-butler** [mrahtz/tensorflow-pos-tagger#3]
Working on an Arabic name recognition implementation of this, any workaround for this error you know of would be appreciated.

**Comment by mrahtz** [comment]
Hey, I don't think I'll have time to look into this at the moment, but if you do manage to fix it I'd be happy to accept a pull request.

**Comment by gary-butler** [comment]
I came up with a work around after looking into the same error on some other repositories. It's pretty niche to my situation though. I figured out that I was unintentionally having tflearn put objects that aren't tensors into TensorFlow collections. I fixed it by adding this line before saving my model.
`del tf.get_collection_ref(tf.GraphKeys.TRAIN_OPS)[:]`
